language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
virtualenv:
    system_site_packages: true
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libatlas-dev liblapack-dev gfortran python-numpy python-scipy
    - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then sudo apt-get install -qq python3-numpy python3-scipy; fi

install:
    - python setup.py install
script: python setup.py test
