language: python
matrix:
  include:
    - python: 2.6
      env:
        - SCIPY_VERSION="0.7.0"
        - NUMPY_VERSION="1.3.0"
    - python: 2.6
      env:
        - SCIPY_VERSION="0.14.0"
        - NUMPY_VERSION="1.9.1"
    - python: 2.7
      env:
        - SCIPY_VERSION="0.7.0
        - NUMPY_VERSION="1.4.1"
    - python: 2.7
      env:
        - SCIPY_VERSION="0.14.0
        - NUMPY_VERSION="1.9.1"
    - python: 3.3
      env:
        - SCIPY_VERSION="0.7.0
        - NUMPY_VERSION="1.4.1"
    - python: 3.3
      env:
        - SCIPY_VERSION="0.14.0
        - NUMPY_VERSION="1.9.1"
    - python: 3.4
      env:
        - SCIPY_VERSION="0.7.0
        - NUMPY_VERSION="1.4.1"
    - python: 3.4
      env:
        - SCIPY_VERSION="0.14.0
        - NUMPY_VERSION="1.9.1"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
install:
  - wget http://sourceforge.net/projects/numpy/files/NumPy/$NUMPY_VERSION/numpy-$NUMPY_VERSION.tar.gz/download -O numpy-$NUMPY_VERSION.tar.gz
  - wget http://sourceforge.net/projects/scipy/files/scipy/$SCIPY_VERSION/scipy-$SCIPY_VERSION.tar.gz/download -O scipy-$SCIPY_VERSION.tar.gz
  - tar xzf scipy-$SCIPY_VERSION.tar.gz
  - tar xzf numpy-$NUMPY_VERSION.tar.gz
  - pip install -e ./numpy-$NUMPY_VERSION
  - pip install -e ./scipy-$SCIPY_VERSION
  - pip install -e .
script: python setup.py test
